### ISSUE TITLE
Double number row displayed for password fields

### ISSUE THREAD

**Issue by lukesky12** [kiideveloper/kiikeyboard2#3]
When entering passwords, the number row is displayed twice. The 2nd number row is probably the original AOSP one which should be suppressed if the Kii keyboard number row is turned on.

Using version 1.02 and I'm on Nexus 6p with Android 6.01

**Comment by kiideveloper** [comment]
thanks for your suggestion, this is a good idea

**Comment by lukesky12** [comment]
Fixed in kii keyboard version 1.03 alpha
