### ISSUE TITLE
[Bug] No quick change in landscape...

### ISSUE THREAD

**Issue by xnaas** [kiideveloper/kiikeyboard2#6]
Quick change does not appear to work in landscape. Says premium is required, but as far as I can tell, there is no option to purchase premium.

If there will be premium in the future, I would still like to see the feature usable until a premium option is implemented so it can be tested.

![Screenshot courtesy of a buddy.](http://i.imgur.com/FknTqNV.png)

**Comment by kiideveloper** [comment]
Thanks for the report, this will be fixed next update
