### ISSUE TITLE
[Feature Request] AMOLED Black Keyboard Theme

### ISSUE THREAD

**Issue by xnaas** [kiideveloper/kiikeyboard2#7]
Hey, I know you have https://wantoo.io/kii-keyboard-2/ideas/ setup for ideas...but I prefer GitHub, unless you have any objections. If so, let me know and I'll redirect my feature requests/ideas over to `wantoo`...~~though I'd rather not make _yet another_ account for something.~~

That out of the way, I'd like a AMOLED black keyboard theme as one of the built-in options. For inspiration, refer to Google's below:

![Google AMOLED black keyboard theme](http://i.imgur.com/XxhxbyD.png)

**Comment by anxiousdog** [comment]
Agreed on both points. Would like to include both bugs and suggestions here, and awesome theme!

**Comment by xnaas** [comment]
AMOLED is ❤

**Comment by xnaas** [comment]
Closing out insanely old issue.
