### ISSUE TITLE
Holding H for Asterisk No Longer Works

### ISSUE THREAD

**Issue by xnaas** [kiideveloper/kiikeyboard2#9]
## Expected Behavior

When I hold "H", I should get an asterisk after my set hold time.
## Current Behavior

No asterisk. Works with all other keys and their secondary functions.
## Steps to Reproduce
1. Hold H for it's second function/character. Does not work.
2. Try with any other key and it works.

Holding G: ![Holding G](http://i.imgur.com/XheX2jq.png)
Holding X: ![Holding X](http://i.imgur.com/gCmH3rv.png)
Holding N: ![Holding N](http://i.imgur.com/FlpvPfz.png)
Holding H: ![Holding H](http://i.imgur.com/2abk5U8.png)
## Context

I hate having to swap to the symbols/numbers board just for an asterisk (which I use very often)... :)
## Your Environment
- Android Version used: 7.0
- Phone/tablet name and model: Nexus 6P
- Language and keyboard layout: English, Full Layout, Standard US keyboard

**Comment by xnaas** [comment]
Note: This did work just fine before the latest update (could have sworn it was a different key before H...but I could just be crazy). 😄

**Comment by EnigmaRaptor** [comment]
Confirming issue.  Same hardware and software setup.

**Comment by MyLittleLoves** [comment]
I'm having the same issue on both my phone & tablet. 

Phone model is LG V10 (H-901; T-Mobile) running 6.0 & tablet model is Samsung Galaxy Note Pro (SM-P907A; AT&T) running 4.4.2

**Comment by Empanser** [comment]
Same issue on Moto X 2013, 5.1

**Comment by nh1402** [comment]
Same issue Nexus 5, Android 7.1,   1.0.4 alpha

**Comment by cortextually** [comment]
Can confirm, same issue. 7.0 Nexus 5X

**Comment by MarSoft** [comment]
Can confirm. Xiaomi Mi5, MIUI Global 8.1.2.0 / Android 6.0.1

**Comment by n01101110n** [comment]
Confirm issue on HTC 10, Android 7

**Comment by PolarisTLX** [comment]
Confirm same issue with the "H" key. LG G5 Android 7.0.

**Comment by Operator801** [comment]
Same issue on ZTE Blade X Max

**Comment by Operator801** [comment]
Same issue on ZTE Blade X Max, android 7.1.1

**Comment by PolarisTLX** [comment]
I am a programmer with some experience contributing to open source projects, fixing bugs then creating pull requests etc.  

I am happy to give it a shot and I believe I would be able to fix this tiny bug. 

I would just need access to the source code, as this repo seems to only have .rst files  and documentation as opposed to the actual code (unless I'm missing something?).

**Comment by pbanj** [comment]
Really wish this bug had gotten fixed before the dev gave up.

**Comment by xnaas** [comment]
Closing out insanely old issue.

Also of note: project is dead. Oh well.

**Comment by Operator801** [comment]
What do I do about the money that I already spent for this software that I can't download or use now?

**Comment by exarobibliologist** [comment]
This is literally the only issue I have with Kii!

Will there ever be an update to this (still amazing) keyboard?

**Comment by pbanj** [comment]
Nope it's dead
